import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import Navbar from "@/components/Navbar";
/**
 * 这是全局布局组件，它包含了所有页面的公共布局。都要展示的内容一般都要放在这里。
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {/* 这里放全局导航栏 */}
          <Navbar />
          {/* 页面主体 */}
          <div className="pt-16">
            {/* 避免导航栏遮挡内容 */}
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
